module Langfuse
  module Resources
    class API
      class Public
        class V2
          class Prompts
            def create:
              (
                Langfuse::Models::API::Public::V2::PromptCreateParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::V2::prompt
              | (
                name: String,
                prompt: String,
                commit_message: String?,
                config: top,
                labels: ::Array[String]?,
                tags: ::Array[String]?,
                type: Langfuse::Models::API::Public::V2::PromptCreateParams::type_,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::V2::prompt

            def retrieve:
              (
                String prompt_name,
                ?Langfuse::Models::API::Public::V2::PromptRetrieveParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::V2::prompt
              | (
                String prompt_name,
                label: String?,
                version: Integer?,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::V2::prompt

            def list:
              (
                ?Langfuse::Models::API::Public::V2::PromptListParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::V2::PromptListResponse
              | (
                from_updated_at: Time?,
                label: String?,
                limit: Integer?,
                name: String?,
                page: Integer?,
                tag: String?,
                to_updated_at: Time?,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::V2::PromptListResponse

            def update_labels:
              (
                Integer version,
                Langfuse::Models::API::Public::V2::PromptUpdateLabelsParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::V2::prompt
              | (
                Integer version,
                name: String,
                new_labels: ::Array[String],
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::V2::prompt

            def initialize: (client: Langfuse::Client) -> void
          end
        end
      end
    end
  end
end
