module Langfuse
  module Models
    module API
      module Public
        
        class AnnotationQueueObjectType = AnnotationQueues::AnnotationQueueObjectType

        module AnnotationQueues
          type annotation_queue_object_type = :TRACE | :OBSERVATION

          class AnnotationQueueObjectType < Langfuse::Enum
            TRACE: :TRACE
            OBSERVATION: :OBSERVATION

            def self.values: -> ::Array[Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_object_type]
          end
        end
      end
    end
  end
end
