module Langfuse
  module Models
    module API
      module Public
        
        class AnnotationQueueStatus = AnnotationQueues::AnnotationQueueStatus

        module AnnotationQueues
          type annotation_queue_status = :PENDING | :COMPLETED

          class AnnotationQueueStatus < Langfuse::Enum
            PENDING: :PENDING
            COMPLETED: :COMPLETED

            def self.values: -> ::Array[Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status]
          end
        end
      end
    end
  end
end
