module Langfuse
  module Models
    module API
      module Public
        
        class AnnotationQueueItem = AnnotationQueues::AnnotationQueueItem

        module AnnotationQueues
          type annotation_queue_item =
            {
              id: String,
              created_at: Time,
              object_id_: String,
              object_type: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_object_type,
              queue_id: String,
              status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status,
              updated_at: Time,
              completed_at: Time?
            }

          class AnnotationQueueItem < Langfuse::BaseModel
            attr_accessor id: String

            attr_accessor created_at: Time

            attr_accessor object_id_: String

            attr_accessor object_type: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_object_type

            attr_accessor queue_id: String

            attr_accessor status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status

            attr_accessor updated_at: Time

            attr_accessor completed_at: Time?

            def initialize:
              (
                id: String,
                created_at: Time,
                object_id_: String,
                object_type: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_object_type,
                queue_id: String,
                status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status,
                updated_at: Time,
                completed_at: Time?
              ) -> void
              | (
                ?Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_item
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_item
          end
        end
      end
    end
  end
end
