module Langfuse
  module Models
    module API
      module Public
        module AnnotationQueues
          type item_update_params =
            {
              queue_id: String,
              status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status?
            }
            & Langfuse::request_parameters

          class ItemUpdateParams < Langfuse::BaseModel
            extend Langfuse::RequestParameters::Converter
            include Langfuse::RequestParameters

            attr_accessor queue_id: String

            attr_accessor status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status?

            def initialize:
              (
                queue_id: String,
                status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status?,
                request_options: Langfuse::request_opts
              ) -> void
              | (
                ?Langfuse::Models::API::Public::AnnotationQueues::item_update_params
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::Public::AnnotationQueues::item_update_params
          end
        end
      end
    end
  end
end
