module Langfuse
  module Resources
    class API
      class Public
        class AnnotationQueues
          class Items
            def create:
              (
                String queue_id,
                Langfuse::Models::API::Public::AnnotationQueues::ItemCreateParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::AnnotationQueues::AnnotationQueueItem
              | (
                String queue_id,
                object_id_: String,
                object_type: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_object_type,
                status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status?,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::AnnotationQueues::AnnotationQueueItem

            def retrieve:
              (
                String item_id,
                Langfuse::Models::API::Public::AnnotationQueues::ItemRetrieveParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::AnnotationQueues::AnnotationQueueItem
              | (
                String item_id,
                queue_id: String,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::AnnotationQueues::AnnotationQueueItem

            def update:
              (
                String item_id,
                Langfuse::Models::API::Public::AnnotationQueues::ItemUpdateParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::AnnotationQueues::AnnotationQueueItem
              | (
                String item_id,
                queue_id: String,
                status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status?,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::AnnotationQueues::AnnotationQueueItem

            def list:
              (
                String queue_id,
                ?Langfuse::Models::API::Public::AnnotationQueues::ItemListParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::AnnotationQueues::ItemListResponse
              | (
                String queue_id,
                limit: Integer?,
                page: Integer?,
                status: Langfuse::Models::API::Public::AnnotationQueues::annotation_queue_status?,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::AnnotationQueues::ItemListResponse

            def delete:
              (
                String item_id,
                Langfuse::Models::API::Public::AnnotationQueues::ItemDeleteParams
                | ::Hash[Symbol, top] params
              ) -> Langfuse::Models::API::Public::AnnotationQueues::ItemDeleteResponse
              | (
                String item_id,
                queue_id: String,
                request_options: Langfuse::request_opts
              ) -> Langfuse::Models::API::Public::AnnotationQueues::ItemDeleteResponse

            def initialize: (client: Langfuse::Client) -> void
          end
        end
      end
    end
  end
end
