# frozen_string_literal: true

module Langfuse
  module Models
    module API
      module Public
        class ScoreConfigCreateParams < Langfuse::BaseModel
          # @!parse
          #   extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          # @!attribute data_type
          #
          #   @return [Symbol, Langfuse::Models::API::Public::ScoreDataType]
          required :data_type, enum: -> { Langfuse::Models::API::Public::ScoreDataType }, api_name: :dataType

          # @!attribute name
          #
          #   @return [String]
          required :name, String

          # @!attribute categories
          #   Configure custom categories for categorical scores. Pass a list of objects with
          #     `label` and `value` properties. Categories are autogenerated for boolean configs
          #     and cannot be passed
          #
          #   @return [Array<Langfuse::Models::API::Public::ConfigCategory>, nil]
          optional :categories, -> { Langfuse::ArrayOf[Langfuse::Models::API::Public::ConfigCategory] }, nil?: true

          # @!attribute description
          #   Description is shown across the Langfuse UI and can be used to e.g. explain the
          #     config categories in detail, why a numeric range was set, or provide additional
          #     context on config name or usage
          #
          #   @return [String, nil]
          optional :description, String, nil?: true

          # @!attribute max_value
          #   Configure a maximum value for numerical scores. If not set, the maximum value
          #     defaults to +∞
          #
          #   @return [Float, nil]
          optional :max_value, Float, api_name: :maxValue, nil?: true

          # @!attribute min_value
          #   Configure a minimum value for numerical scores. If not set, the minimum value
          #     defaults to -∞
          #
          #   @return [Float, nil]
          optional :min_value, Float, api_name: :minValue, nil?: true

          # @!parse
          #   # @param data_type [Symbol, Langfuse::Models::API::Public::ScoreDataType]
          #   # @param name [String]
          #   # @param categories [Array<Langfuse::Models::API::Public::ConfigCategory>, nil]
          #   # @param description [String, nil]
          #   # @param max_value [Float, nil]
          #   # @param min_value [Float, nil]
          #   # @param request_options [Langfuse::RequestOptions, Hash{Symbol=>Object}]
          #   #
          #   def initialize(
          #     data_type:,
          #     name:,
          #     categories: nil,
          #     description: nil,
          #     max_value: nil,
          #     min_value: nil,
          #     request_options: {},
          #     **
          #   )
          #     super
          #   end

          # def initialize: (Hash | Langfuse::BaseModel) -> void
        end
      end
    end
  end
end
