module Langfuse
  class Client < Langfuse::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader username: String

    attr_reader password: String

    attr_reader api: Langfuse::Resources::API

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      base_url: String?,
      username: String?,
      password: String?,
      max_retries: Integer,
      timeout: Float,
      initial_retry_delay: Float,
      max_retry_delay: Float
    ) -> void
  end
end
