module Langfuse
  class Error < StandardError
    attr_reader cause: StandardError?
  end

  class ConversionError < Langfuse::Error
  end

  class APIError < Langfuse::Error
    attr_reader url: URI::Generic

    attr_reader status: Integer?

    attr_reader body: top?

    def initialize: (
      url: URI::Generic,
      status: Integer?,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIConnectionError < Langfuse::APIError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APITimeoutError < Langfuse::APIConnectionError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIStatusError < Langfuse::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class BadRequestError < Langfuse::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Langfuse::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Langfuse::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Langfuse::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Langfuse::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Langfuse::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Langfuse::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < Langfuse::APIStatusError
    HTTP_STATUS: Range[Integer]
  end
end
