module Langfuse
  module Models
    module API
      module Public
        module V2
          type base_prompt =
            {
              config: top,
              labels: ::Array[String],
              name: String,
              tags: ::Array[String],
              version: Integer,
              commit_message: String?,
              resolution_graph: ::Hash[Symbol, top]?
            }

          class BasePrompt < Langfuse::BaseModel
            attr_accessor config: top

            attr_accessor labels: ::Array[String]

            attr_accessor name: String

            attr_accessor tags: ::Array[String]

            attr_accessor version: Integer

            attr_accessor commit_message: String?

            attr_accessor resolution_graph: ::Hash[Symbol, top]?

            def initialize:
              (
                config: top,
                labels: ::Array[String],
                name: String,
                tags: ::Array[String],
                version: Integer,
                commit_message: String?,
                resolution_graph: ::Hash[Symbol, top]?
              ) -> void
              | (
                ?Langfuse::Models::API::Public::V2::base_prompt
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::Public::V2::base_prompt
          end
        end
      end
    end
  end
end
