module Langfuse
  module Models
    module API
      module Public
        module V2
          type chat_message = { content: String, role: String }

          class ChatMessage < Langfuse::BaseModel
            attr_accessor content: String

            attr_accessor role: String

            def initialize:
              (content: String, role: String) -> void
              | (
                ?Langfuse::Models::API::Public::V2::chat_message
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::Public::V2::chat_message
          end
        end
      end
    end
  end
end
