module Langfuse
  module Models
    module API
      module Public
        module V2
          type prompt =
            Langfuse::Models::API::Public::V2::Prompt::UnionMember0
            | Langfuse::Models::API::Public::V2::Prompt::UnionMember1

          class Prompt < Langfuse::Union
            type union_member0 =
              {
                type: Langfuse::Models::API::Public::V2::Prompt::UnionMember0::type_
              }

            class UnionMember0 < Langfuse::Models::API::Public::V2::BasePrompt
              attr_reader type: Langfuse::Models::API::Public::V2::Prompt::UnionMember0::type_?

              def type=: (
                Langfuse::Models::API::Public::V2::Prompt::UnionMember0::type_
              ) -> Langfuse::Models::API::Public::V2::Prompt::UnionMember0::type_

              def initialize:
                (
                  type: Langfuse::Models::API::Public::V2::Prompt::UnionMember0::type_
                ) -> void
                | (
                  ?Langfuse::Models::API::Public::V2::Prompt::union_member0
                  | Langfuse::BaseModel data
                ) -> void

              def to_hash: -> Langfuse::Models::API::Public::V2::Prompt::union_member0

              type type_ = :chat

              class Type < Langfuse::Enum
                CHAT: :chat

                def self.values: -> ::Array[Langfuse::Models::API::Public::V2::Prompt::UnionMember0::type_]
              end
            end

            type union_member1 =
              {
                type: Langfuse::Models::API::Public::V2::Prompt::UnionMember1::type_
              }

            class UnionMember1 < Langfuse::Models::API::Public::V2::BasePrompt
              attr_reader type: Langfuse::Models::API::Public::V2::Prompt::UnionMember1::type_?

              def type=: (
                Langfuse::Models::API::Public::V2::Prompt::UnionMember1::type_
              ) -> Langfuse::Models::API::Public::V2::Prompt::UnionMember1::type_

              def initialize:
                (
                  type: Langfuse::Models::API::Public::V2::Prompt::UnionMember1::type_
                ) -> void
                | (
                  ?Langfuse::Models::API::Public::V2::Prompt::union_member1
                  | Langfuse::BaseModel data
                ) -> void

              def to_hash: -> Langfuse::Models::API::Public::V2::Prompt::union_member1

              type type_ = :text

              class Type < Langfuse::Enum
                TEXT: :text

                def self.values: -> ::Array[Langfuse::Models::API::Public::V2::Prompt::UnionMember1::type_]
              end
            end

            private def self.variants: -> [[nil, Langfuse::Models::API::Public::V2::Prompt::UnionMember0], [nil, Langfuse::Models::API::Public::V2::Prompt::UnionMember1]]
          end
        end
      end
    end
  end
end
