module Langfuse
  module Models
    module API
      module Public
        module V2
          type prompt_retrieve_params =
            { label: String?, version: Integer? } & Langfuse::request_parameters

          class PromptRetrieveParams < Langfuse::BaseModel
            extend Langfuse::RequestParameters::Converter
            include Langfuse::RequestParameters

            attr_accessor label: String?

            attr_accessor version: Integer?

            def initialize:
              (
                label: String?,
                version: Integer?,
                request_options: Langfuse::request_opts
              ) -> void
              | (
                ?Langfuse::Models::API::Public::V2::prompt_retrieve_params
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::Public::V2::prompt_retrieve_params
          end
        end
      end
    end
  end
end
