module Langfuse
  module Models
    module API
      module Public
        module V2
          type prompt_create_params =
            {
              name: String,
              prompt: String,
              commit_message: String?,
              config: top,
              labels: ::Array[String]?,
              tags: ::Array[String]?,
              type: Langfuse::Models::API::Public::V2::PromptCreateParams::type_
            }
            & Langfuse::request_parameters

          class PromptCreateParams < Langfuse::BaseModel
            extend Langfuse::RequestParameters::Converter
            include Langfuse::RequestParameters

            attr_accessor name: String

            attr_accessor prompt: String

            attr_accessor commit_message: String?

            attr_reader config: top?

            def config=: (top) -> top

            attr_accessor labels: ::Array[String]?

            attr_accessor tags: ::Array[String]?

            attr_reader type: Langfuse::Models::API::Public::V2::PromptCreateParams::type_?

            def type=: (
              Langfuse::Models::API::Public::V2::PromptCreateParams::type_
            ) -> Langfuse::Models::API::Public::V2::PromptCreateParams::type_

            def initialize:
              (
                name: String,
                prompt: String,
                commit_message: String?,
                config: top,
                labels: ::Array[String]?,
                tags: ::Array[String]?,
                type: Langfuse::Models::API::Public::V2::PromptCreateParams::type_,
                request_options: Langfuse::request_opts
              ) -> void
              | (
                ?Langfuse::Models::API::Public::V2::prompt_create_params
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::Public::V2::prompt_create_params

            type type_ = :text

            class Type < Langfuse::Enum
              TEXT: :text

              def self.values: -> ::Array[Langfuse::Models::API::Public::V2::PromptCreateParams::type_]
            end
          end
        end
      end
    end
  end
end
