module Langfuse
  module Resources
    class API
      class Public
        class Comments
          def create:
            (
              Langfuse::Models::API::Public::CommentCreateParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::CommentCreateResponse
            | (
              content: String,
              object_id_: String,
              object_type: String,
              project_id: String,
              author_user_id: String?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::CommentCreateResponse

          def retrieve:
            (
              String comment_id,
              ?Langfuse::Models::API::Public::CommentRetrieveParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::Comment
            | (
              String comment_id,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::Comment

          def list:
            (
              ?Langfuse::Models::API::Public::CommentListParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::CommentListResponse
            | (
              author_user_id: String?,
              limit: Integer?,
              object_id_: String?,
              object_type: String?,
              page: Integer?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::CommentListResponse

          def initialize: (client: Langfuse::Client) -> void
        end
      end
    end
  end
end
