module Langfuse
  module Resources
    class API
      class Public
        class Media
          def retrieve:
            (
              String media_id,
              ?Langfuse::Models::API::Public::MediaRetrieveParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::MediaRetrieveResponse
            | (
              String media_id,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::MediaRetrieveResponse

          def update:
            (
              String media_id,
              Langfuse::Models::API::Public::MediaUpdateParams
              | ::Hash[Symbol, top] params
            ) -> nil
            | (
              String media_id,
              uploaded_at: Time,
              upload_http_status: Integer,
              upload_http_error: String?,
              upload_time_ms: Integer?,
              request_options: Langfuse::request_opts
            ) -> nil

          def create_upload_url:
            (
              Langfuse::Models::API::Public::MediaCreateUploadURLParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::MediaCreateUploadURLResponse
            | (
              content_length: Integer,
              content_type: Langfuse::Models::API::Public::MediaCreateUploadURLParams::content_type,
              field: String,
              sha256_hash: String,
              trace_id: String,
              observation_id: String?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::MediaCreateUploadURLResponse

          def initialize: (client: Langfuse::Client) -> void
        end
      end
    end
  end
end
