module Langfuse
  module Resources
    class API
      class Public
        class Metrics
          def get_daily:
            (
              ?Langfuse::Models::API::Public::MetricGetDailyParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::MetricGetDailyResponse
            | (
              environment: ::Array[String?],
              from_timestamp: Time?,
              limit: Integer?,
              page: Integer?,
              tags: ::Array[String?],
              to_timestamp: Time?,
              trace_name: String?,
              user_id: String?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::MetricGetDailyResponse

          def initialize: (client: Langfuse::Client) -> void
        end
      end
    end
  end
end
