module Langfuse
  module Resources
    class API
      class Public
        class Models
          def create:
            (
              Langfuse::Models::API::Public::ModelCreateParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::Model
            | (
              match_pattern: String,
              model_name: String,
              input_price: Float?,
              output_price: Float?,
              start_date: Time?,
              tokenizer_config: top,
              tokenizer_id: String?,
              total_price: Float?,
              unit: Langfuse::Models::API::Public::model_usage_unit?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::Model

          def retrieve:
            (
              String id,
              ?Langfuse::Models::API::Public::ModelRetrieveParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::Model
            | (
              String id,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::Model

          def list:
            (
              ?Langfuse::Models::API::Public::ModelListParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::ModelListResponse
            | (
              limit: Integer?,
              page: Integer?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::ModelListResponse

          def delete:
            (
              String id,
              ?Langfuse::Models::API::Public::ModelDeleteParams
              | ::Hash[Symbol, top] params
            ) -> nil
            | (String id, request_options: Langfuse::request_opts) -> nil

          def initialize: (client: Langfuse::Client) -> void
        end
      end
    end
  end
end
