module Langfuse
  module Resources
    class API
      class Public
        class Traces
          def retrieve:
            (
              String trace_id,
              ?Langfuse::Models::API::Public::TraceRetrieveParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::TraceRetrieveResponse
            | (
              String trace_id,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::TraceRetrieveResponse

          def list:
            (
              ?Langfuse::Models::API::Public::TraceListParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::TraceListResponse
            | (
              environment: ::Array[String?],
              from_timestamp: Time?,
              limit: Integer?,
              name: String?,
              order_by: String?,
              page: Integer?,
              release: String?,
              session_id: String?,
              tags: ::Array[String?],
              to_timestamp: Time?,
              user_id: String?,
              version: String?,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::TraceListResponse

          def delete:
            (
              String trace_id,
              ?Langfuse::Models::API::Public::TraceDeleteParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::DeleteTraceResponse
            | (
              String trace_id,
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::DeleteTraceResponse

          def delete_multiple:
            (
              Langfuse::Models::API::Public::TraceDeleteMultipleParams
              | ::Hash[Symbol, top] params
            ) -> Langfuse::Models::API::Public::DeleteTraceResponse
            | (
              trace_ids: ::Array[String],
              request_options: Langfuse::request_opts
            ) -> Langfuse::Models::API::Public::DeleteTraceResponse

          def initialize: (client: Langfuse::Client) -> void
        end
      end
    end
  end
end
