module Langfuse
  module Models
    module API
      type base_event = { id: String, timestamp: String, metadata: top }

      class BaseEvent < Langfuse::BaseModel
        attr_accessor id: String

        attr_accessor timestamp: String

        attr_reader metadata: top?

        def metadata=: (top) -> top

        def initialize:
          (id: String, timestamp: String, metadata: top) -> void
          | (
            ?Langfuse::Models::API::base_event | Langfuse::BaseModel data
          ) -> void

        def to_hash: -> Langfuse::Models::API::base_event
      end
    end
  end
end
