module Langfuse
  module Models
    module API
      type create_event_body = { id: String? }

      class CreateEventBody < Langfuse::Models::API::OptionalObservationBody
        attr_accessor id: String?

        def initialize:
          (id: String?) -> void
          | (
            ?Langfuse::Models::API::create_event_body | Langfuse::BaseModel data
          ) -> void

        def to_hash: -> Langfuse::Models::API::create_event_body
      end
    end
  end
end
