module Langfuse
  module Models
    module API
      type observation_body =
        {
          type: Langfuse::Models::API::ObservationBody::type_,
          id: String?,
          completion_start_time: Time?,
          end_time: Time?,
          environment: String?,
          input: top,
          level: Langfuse::Models::API::Public::observation_level?,
          metadata: top,
          model: String?,
          model_parameters: ::Hash[Symbol, Langfuse::Models::API::ObservationBody::model_parameter?]?,
          name: String?,
          output: top,
          parent_observation_id: String?,
          start_time: Time?,
          status_message: String?,
          trace_id: String?,
          usage: Langfuse::Models::API::Public::Usage?,
          version: String?
        }

      class ObservationBody < Langfuse::BaseModel
        attr_accessor type: Langfuse::Models::API::ObservationBody::type_

        attr_accessor id: String?

        attr_accessor completion_start_time: Time?

        attr_accessor end_time: Time?

        attr_accessor environment: String?

        attr_reader input: top?

        def input=: (top) -> top

        attr_accessor level: Langfuse::Models::API::Public::observation_level?

        attr_reader metadata: top?

        def metadata=: (top) -> top

        attr_accessor model: String?

        attr_accessor model_parameters: ::Hash[Symbol, Langfuse::Models::API::ObservationBody::model_parameter?]?

        attr_accessor name: String?

        attr_reader output: top?

        def output=: (top) -> top

        attr_accessor parent_observation_id: String?

        attr_accessor start_time: Time?

        attr_accessor status_message: String?

        attr_accessor trace_id: String?

        attr_accessor usage: Langfuse::Models::API::Public::Usage?

        attr_accessor version: String?

        def initialize:
          (
            type: Langfuse::Models::API::ObservationBody::type_,
            id: String?,
            completion_start_time: Time?,
            end_time: Time?,
            environment: String?,
            input: top,
            level: Langfuse::Models::API::Public::observation_level?,
            metadata: top,
            model: String?,
            model_parameters: ::Hash[Symbol, Langfuse::Models::API::ObservationBody::model_parameter?]?,
            name: String?,
            output: top,
            parent_observation_id: String?,
            start_time: Time?,
            status_message: String?,
            trace_id: String?,
            usage: Langfuse::Models::API::Public::Usage?,
            version: String?
          ) -> void
          | (
            ?Langfuse::Models::API::observation_body | Langfuse::BaseModel data
          ) -> void

        def to_hash: -> Langfuse::Models::API::observation_body

        type type_ = :SPAN | :GENERATION | :EVENT

        class Type < Langfuse::Enum
          SPAN: :SPAN
          GENERATION: :GENERATION
          EVENT: :EVENT

          def self.values: -> ::Array[Langfuse::Models::API::ObservationBody::type_]
        end

        type model_parameter = (String | Integer | bool | ::Array[String])?

        class ModelParameter < Langfuse::Union
          type string_array = ::Array[String]?

          StringArray: string_array

          private def self.variants: -> [[nil, String], [nil, Integer], [nil, bool], [nil, ::Array[String]]]
        end
      end
    end
  end
end
