module Langfuse
  module Models
    module API
      type public_batch_ingestion_params =
        {
          batch: ::Array[Langfuse::Models::API::PublicBatchIngestionParams::batch],
          metadata: top
        }
        & Langfuse::request_parameters

      class PublicBatchIngestionParams < Langfuse::BaseModel
        extend Langfuse::RequestParameters::Converter
        include Langfuse::RequestParameters

        attr_accessor batch: ::Array[Langfuse::Models::API::PublicBatchIngestionParams::batch]

        attr_reader metadata: top?

        def metadata=: (top) -> top

        def initialize:
          (
            batch: ::Array[Langfuse::Models::API::PublicBatchIngestionParams::batch],
            metadata: top,
            request_options: Langfuse::request_opts
          ) -> void
          | (
            ?Langfuse::Models::API::public_batch_ingestion_params
            | Langfuse::BaseModel data
          ) -> void

        def to_hash: -> Langfuse::Models::API::public_batch_ingestion_params

        type batch =
          Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8
          | Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9

        class Batch < Langfuse::Union
          type union_member0 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0::type_
            }

          class UnionMember0 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member0
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member0

            type type_ = :"trace-create"

            class Type < Langfuse::Enum
              TRACE_CREATE: :"trace-create"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0::type_]
            end
          end

          type union_member1 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1::type_
            }

          class UnionMember1 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member1
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member1

            type type_ = :"score-create"

            class Type < Langfuse::Enum
              SCORE_CREATE: :"score-create"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1::type_]
            end
          end

          type union_member2 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2::type_
            }

          class UnionMember2 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member2
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member2

            type type_ = :"span-create"

            class Type < Langfuse::Enum
              SPAN_CREATE: :"span-create"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2::type_]
            end
          end

          type union_member3 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3::type_
            }

          class UnionMember3 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member3
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member3

            type type_ = :"span-update"

            class Type < Langfuse::Enum
              SPAN_UPDATE: :"span-update"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3::type_]
            end
          end

          type union_member4 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4::type_
            }

          class UnionMember4 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member4
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member4

            type type_ = :"generation-create"

            class Type < Langfuse::Enum
              GENERATION_CREATE: :"generation-create"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4::type_]
            end
          end

          type union_member5 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5::type_
            }

          class UnionMember5 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member5
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member5

            type type_ = :"generation-update"

            class Type < Langfuse::Enum
              GENERATION_UPDATE: :"generation-update"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5::type_]
            end
          end

          type union_member6 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6::type_
            }

          class UnionMember6 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member6
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member6

            type type_ = :"event-create"

            class Type < Langfuse::Enum
              EVENT_CREATE: :"event-create"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6::type_]
            end
          end

          type union_member7 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7::type_
            }

          class UnionMember7 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member7
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member7

            type type_ = :"sdk-log"

            class Type < Langfuse::Enum
              SDK_LOG: :"sdk-log"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7::type_]
            end
          end

          type union_member8 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8::type_
            }

          class UnionMember8 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member8
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member8

            type type_ = :"observation-create"

            class Type < Langfuse::Enum
              OBSERVATION_CREATE: :"observation-create"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8::type_]
            end
          end

          type union_member9 =
            {
              type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9::type_
            }

          class UnionMember9 < Langfuse::Models::API::BaseEvent
            attr_reader type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9::type_?

            def type=: (
              Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9::type_
            ) -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9::type_

            def initialize:
              (
                type: Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9::type_
              ) -> void
              | (
                ?Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member9
                | Langfuse::BaseModel data
              ) -> void

            def to_hash: -> Langfuse::Models::API::PublicBatchIngestionParams::Batch::union_member9

            type type_ = :"observation-update"

            class Type < Langfuse::Enum
              OBSERVATION_UPDATE: :"observation-update"

              def self.values: -> ::Array[Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9::type_]
            end
          end

          private def self.variants: -> [[nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember0], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember1], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember2], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember3], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember4], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember5], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember6], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember7], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember8], [nil, Langfuse::Models::API::PublicBatchIngestionParams::Batch::UnionMember9]]
        end
      end
    end
  end
end
