module Langfuse
  module Models
    module API
      type update_span_body = { end_time: Time? }

      class UpdateSpanBody < Langfuse::Models::API::OptionalObservationBody
        attr_accessor end_time: Time?

        def initialize:
          (end_time: Time?) -> void
          | (
            ?Langfuse::Models::API::update_span_body | Langfuse::BaseModel data
          ) -> void

        def to_hash: -> Langfuse::Models::API::update_span_body
      end
    end
  end
end
