module Langfuse
  module Models
    module API
      module Public
        type annotation_queue =
          {
            id: String,
            created_at: Time,
            name: String,
            score_config_ids: ::Array[String],
            updated_at: Time,
            description: String?
          }

        class AnnotationQueue < Langfuse::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor name: String

          attr_accessor score_config_ids: ::Array[String]

          attr_accessor updated_at: Time

          attr_accessor description: String?

          def initialize:
            (
              id: String,
              created_at: Time,
              name: String,
              score_config_ids: ::Array[String],
              updated_at: Time,
              description: String?
            ) -> void
            | (
              ?Langfuse::Models::API::Public::annotation_queue
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::annotation_queue
        end
      end
    end
  end
end
