module Langfuse
  module Models
    module API
      module Public
        type annotation_queue_retrieve_params =
          {  } & Langfuse::request_parameters

        class AnnotationQueueRetrieveParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          def initialize:
            (request_options: Langfuse::request_opts) -> void
            | (
              ?Langfuse::Models::API::Public::annotation_queue_retrieve_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::annotation_queue_retrieve_params
        end
      end
    end
  end
end
