module Langfuse
  module Models
    module API
      module Public
        type base_score =
          {
            id: String,
            created_at: Time,
            name: String,
            source: Langfuse::Models::API::Public::score_source,
            timestamp: Time,
            trace_id: String,
            updated_at: Time,
            author_user_id: String?,
            comment: String?,
            config_id: String?,
            environment: String?,
            observation_id: String?,
            queue_id: String?
          }

        class BaseScore < Langfuse::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor name: String

          attr_accessor source: Langfuse::Models::API::Public::score_source

          attr_accessor timestamp: Time

          attr_accessor trace_id: String

          attr_accessor updated_at: Time

          attr_accessor author_user_id: String?

          attr_accessor comment: String?

          attr_accessor config_id: String?

          attr_accessor environment: String?

          attr_accessor observation_id: String?

          attr_accessor queue_id: String?

          def initialize:
            (
              id: String,
              created_at: Time,
              name: String,
              source: Langfuse::Models::API::Public::score_source,
              timestamp: Time,
              trace_id: String,
              updated_at: Time,
              author_user_id: String?,
              comment: String?,
              config_id: String?,
              environment: String?,
              observation_id: String?,
              queue_id: String?
            ) -> void
            | (
              ?Langfuse::Models::API::Public::base_score
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::base_score
        end
      end
    end
  end
end
