module Langfuse
  module Models
    module API
      module Public
        type boolean_score = { string_value: String, value: Float }

        class BooleanScore < Langfuse::Models::API::Public::BaseScore
          attr_accessor string_value: String

          attr_accessor value: Float

          def initialize:
            (string_value: String, value: Float) -> void
            | (
              ?Langfuse::Models::API::Public::boolean_score
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::boolean_score
        end
      end
    end
  end
end
