module Langfuse
  module Models
    module API
      module Public
        type comment_create_params =
          {
            content: String,
            object_id_: String,
            object_type: String,
            project_id: String,
            author_user_id: String?
          }
          & Langfuse::request_parameters

        class CommentCreateParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor content: String

          attr_accessor object_id_: String

          attr_accessor object_type: String

          attr_accessor project_id: String

          attr_accessor author_user_id: String?

          def initialize:
            (
              content: String,
              object_id_: String,
              object_type: String,
              project_id: String,
              author_user_id: String?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::comment_create_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::comment_create_params
        end
      end
    end
  end
end
