module Langfuse
  module Models
    module API
      module Public
        type comment_list_params =
          {
            author_user_id: String?,
            limit: Integer?,
            object_id_: String?,
            object_type: String?,
            page: Integer?
          }
          & Langfuse::request_parameters

        class CommentListParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor author_user_id: String?

          attr_accessor limit: Integer?

          attr_accessor object_id_: String?

          attr_accessor object_type: String?

          attr_accessor page: Integer?

          def initialize:
            (
              author_user_id: String?,
              limit: Integer?,
              object_id_: String?,
              object_type: String?,
              page: Integer?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::comment_list_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::comment_list_params
        end
      end
    end
  end
end
