module Langfuse
  module Models
    module API
      module Public
        type config_category = { label: String, value: Float }

        class ConfigCategory < Langfuse::BaseModel
          attr_accessor label: String

          attr_accessor value: Float

          def initialize:
            (label: String, value: Float) -> void
            | (
              ?Langfuse::Models::API::Public::config_category
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::config_category
        end
      end
    end
  end
end
