module Langfuse
  module Models
    module API
      module Public
        type delete_trace_response = { message: String }

        class DeleteTraceResponse < Langfuse::BaseModel
          attr_accessor message: String

          def initialize:
            (message: String) -> void
            | (
              ?Langfuse::Models::API::Public::delete_trace_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::delete_trace_response
        end
      end
    end
  end
end
