module Langfuse
  module Models
    module API
      module Public
        type media_create_upload_url_response =
          { media_id: String, upload_url: String? }

        class MediaCreateUploadURLResponse < Langfuse::BaseModel
          attr_accessor media_id: String

          attr_accessor upload_url: String?

          def initialize:
            (media_id: String, upload_url: String?) -> void
            | (
              ?Langfuse::Models::API::Public::media_create_upload_url_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::media_create_upload_url_response
        end
      end
    end
  end
end
