module Langfuse
  module Models
    module API
      module Public
        type media_retrieve_response =
          {
            content_length: Integer,
            content_type: String,
            media_id: String,
            uploaded_at: Time,
            url: String,
            url_expiry: String
          }

        class MediaRetrieveResponse < Langfuse::BaseModel
          attr_accessor content_length: Integer

          attr_accessor content_type: String

          attr_accessor media_id: String

          attr_accessor uploaded_at: Time

          attr_accessor url: String

          attr_accessor url_expiry: String

          def initialize:
            (
              content_length: Integer,
              content_type: String,
              media_id: String,
              uploaded_at: Time,
              url: String,
              url_expiry: String
            ) -> void
            | (
              ?Langfuse::Models::API::Public::media_retrieve_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::media_retrieve_response
        end
      end
    end
  end
end
