module Langfuse
  module Models
    module API
      module Public
        type media_create_upload_url_params =
          {
            content_length: Integer,
            content_type: Langfuse::Models::API::Public::MediaCreateUploadURLParams::content_type,
            field: String,
            :sha256_hash => String,
            trace_id: String,
            observation_id: String?
          }
          & Langfuse::request_parameters

        class MediaCreateUploadURLParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor content_length: Integer

          attr_accessor content_type: Langfuse::Models::API::Public::MediaCreateUploadURLParams::content_type

          attr_accessor field: String

          attr_accessor sha256_hash: String

          attr_accessor trace_id: String

          attr_accessor observation_id: String?

          def initialize:
            (
              content_length: Integer,
              content_type: Langfuse::Models::API::Public::MediaCreateUploadURLParams::content_type,
              field: String,
              sha256_hash: String,
              trace_id: String,
              observation_id: String?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::media_create_upload_url_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::media_create_upload_url_params

          type content_type =
            :"image/png"
            | :"image/jpeg"
            | :"image/jpg"
            | :"image/webp"
            | :"image/gif"
            | :"image/svg+xml"
            | :"image/tiff"
            | :"image/bmp"
            | :"audio/mpeg"
            | :"audio/mp3"
            | :"audio/wav"
            | :"audio/ogg"
            | :"audio/oga"
            | :"audio/aac"
            | :"audio/mp4"
            | :"audio/flac"
            | :"video/mp4"
            | :"video/webm"
            | :"text/plain"
            | :"text/html"
            | :"text/css"
            | :"text/csv"
            | :"application/pdf"
            | :"application/msword"
            | :"application/vnd.ms-excel"
            | :"application/zip"
            | :"application/json"
            | :"application/xml"
            | :"application/octet-stream"

          class ContentType < Langfuse::Enum
            IMAGE_PNG: :"image/png"
            IMAGE_JPEG: :"image/jpeg"
            IMAGE_JPG: :"image/jpg"
            IMAGE_WEBP: :"image/webp"
            IMAGE_GIF: :"image/gif"
            IMAGE_SVG_XML: :"image/svg+xml"
            IMAGE_TIFF: :"image/tiff"
            IMAGE_BMP: :"image/bmp"
            AUDIO_MPEG: :"audio/mpeg"
            AUDIO_MP3: :"audio/mp3"
            AUDIO_WAV: :"audio/wav"
            AUDIO_OGG: :"audio/ogg"
            AUDIO_OGA: :"audio/oga"
            AUDIO_AAC: :"audio/aac"
            AUDIO_MP4: :"audio/mp4"
            AUDIO_FLAC: :"audio/flac"
            VIDEO_MP4: :"video/mp4"
            VIDEO_WEBM: :"video/webm"
            TEXT_PLAIN: :"text/plain"
            TEXT_HTML: :"text/html"
            TEXT_CSS: :"text/css"
            TEXT_CSV: :"text/csv"
            APPLICATION_PDF: :"application/pdf"
            APPLICATION_MSWORD: :"application/msword"
            APPLICATION_VND_MS_EXCEL: :"application/vnd.ms-excel"
            APPLICATION_ZIP: :"application/zip"
            APPLICATION_JSON: :"application/json"
            APPLICATION_XML: :"application/xml"
            APPLICATION_OCTET_STREAM: :"application/octet-stream"

            def self.values: -> ::Array[Langfuse::Models::API::Public::MediaCreateUploadURLParams::content_type]
          end
        end
      end
    end
  end
end
