module Langfuse
  module Models
    module API
      module Public
        type metric_get_daily_params =
          {
            environment: ::Array[String?],
            from_timestamp: Time?,
            limit: Integer?,
            page: Integer?,
            tags: ::Array[String?],
            to_timestamp: Time?,
            trace_name: String?,
            user_id: String?
          }
          & Langfuse::request_parameters

        class MetricGetDailyParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_reader environment: ::Array[String?]?

          def environment=: (::Array[String?]) -> ::Array[String?]

          attr_accessor from_timestamp: Time?

          attr_accessor limit: Integer?

          attr_accessor page: Integer?

          attr_reader tags: ::Array[String?]?

          def tags=: (::Array[String?]) -> ::Array[String?]

          attr_accessor to_timestamp: Time?

          attr_accessor trace_name: String?

          attr_accessor user_id: String?

          def initialize:
            (
              environment: ::Array[String?],
              from_timestamp: Time?,
              limit: Integer?,
              page: Integer?,
              tags: ::Array[String?],
              to_timestamp: Time?,
              trace_name: String?,
              user_id: String?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::metric_get_daily_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::metric_get_daily_params
        end
      end
    end
  end
end
