module Langfuse
  module Models
    module API
      module Public
        type model_create_params =
          {
            match_pattern: String,
            model_name: String,
            input_price: Float?,
            output_price: Float?,
            start_date: Time?,
            tokenizer_config: top,
            tokenizer_id: String?,
            total_price: Float?,
            unit: Langfuse::Models::API::Public::model_usage_unit?
          }
          & Langfuse::request_parameters

        class ModelCreateParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor match_pattern: String

          attr_accessor model_name: String

          attr_accessor input_price: Float?

          attr_accessor output_price: Float?

          attr_accessor start_date: Time?

          attr_reader tokenizer_config: top?

          def tokenizer_config=: (top) -> top

          attr_accessor tokenizer_id: String?

          attr_accessor total_price: Float?

          attr_accessor unit: Langfuse::Models::API::Public::model_usage_unit?

          def initialize:
            (
              match_pattern: String,
              model_name: String,
              input_price: Float?,
              output_price: Float?,
              start_date: Time?,
              tokenizer_config: top,
              tokenizer_id: String?,
              total_price: Float?,
              unit: Langfuse::Models::API::Public::model_usage_unit?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::model_create_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::model_create_params
        end
      end
    end
  end
end
