module Langfuse
  module Models
    module API
      module Public
        type model_usage_unit =
          :CHARACTERS | :TOKENS | :MILLISECONDS | :SECONDS | :IMAGES | :REQUESTS

        class ModelUsageUnit < Langfuse::Enum
          CHARACTERS: :CHARACTERS
          TOKENS: :TOKENS
          MILLISECONDS: :MILLISECONDS
          SECONDS: :SECONDS
          IMAGES: :IMAGES
          REQUESTS: :REQUESTS

          def self.values: -> ::Array[Langfuse::Models::API::Public::model_usage_unit]
        end
      end
    end
  end
end
