module Langfuse
  module Models
    module API
      module Public
        type numeric_score = { value: Float }

        class NumericScore < Langfuse::Models::API::Public::BaseScore
          attr_accessor value: Float

          def initialize:
            (value: Float) -> void
            | (
              ?Langfuse::Models::API::Public::numeric_score
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::numeric_score
        end
      end
    end
  end
end
