module Langfuse
  module Models
    module API
      module Public
        type observations_view =
          {
            id: String,
            level: Langfuse::Models::API::Public::observation_level,
            start_time: Time,
            type: String,
            calculated_input_cost: Float?,
            calculated_output_cost: Float?,
            calculated_total_cost: Float?,
            completion_start_time: Time?,
            cost_details: ::Hash[Symbol, Float]?,
            end_time: Time?,
            environment: String?,
            input: top,
            input_price: Float?,
            latency: Float?,
            metadata: top,
            model: String?,
            model_id: String?,
            model_parameters: ::Hash[Symbol, Langfuse::Models::API::Public::ObservationsView::model_parameter?]?,
            name: String?,
            output: top,
            output_price: Float?,
            parent_observation_id: String?,
            prompt_id: String?,
            prompt_name: String?,
            prompt_version: Integer?,
            status_message: String?,
            time_to_first_token: Float?,
            total_price: Float?,
            trace_id: String?,
            usage: Langfuse::Models::API::Public::Usage?,
            usage_details: ::Hash[Symbol, Integer]?,
            version: String?
          }

        class ObservationsView < Langfuse::BaseModel
          attr_accessor id: String

          attr_accessor level: Langfuse::Models::API::Public::observation_level

          attr_accessor start_time: Time

          attr_accessor type: String

          attr_accessor calculated_input_cost: Float?

          attr_accessor calculated_output_cost: Float?

          attr_accessor calculated_total_cost: Float?

          attr_accessor completion_start_time: Time?

          attr_accessor cost_details: ::Hash[Symbol, Float]?

          attr_accessor end_time: Time?

          attr_accessor environment: String?

          attr_reader input: top?

          def input=: (top) -> top

          attr_accessor input_price: Float?

          attr_accessor latency: Float?

          attr_reader metadata: top?

          def metadata=: (top) -> top

          attr_accessor model: String?

          attr_accessor model_id: String?

          attr_accessor model_parameters: ::Hash[Symbol, Langfuse::Models::API::Public::ObservationsView::model_parameter?]?

          attr_accessor name: String?

          attr_reader output: top?

          def output=: (top) -> top

          attr_accessor output_price: Float?

          attr_accessor parent_observation_id: String?

          attr_accessor prompt_id: String?

          attr_accessor prompt_name: String?

          attr_accessor prompt_version: Integer?

          attr_accessor status_message: String?

          attr_accessor time_to_first_token: Float?

          attr_accessor total_price: Float?

          attr_accessor trace_id: String?

          attr_accessor usage: Langfuse::Models::API::Public::Usage?

          attr_accessor usage_details: ::Hash[Symbol, Integer]?

          attr_accessor version: String?

          def initialize:
            (
              id: String,
              level: Langfuse::Models::API::Public::observation_level,
              start_time: Time,
              type: String,
              calculated_input_cost: Float?,
              calculated_output_cost: Float?,
              calculated_total_cost: Float?,
              completion_start_time: Time?,
              cost_details: ::Hash[Symbol, Float]?,
              end_time: Time?,
              environment: String?,
              input: top,
              input_price: Float?,
              latency: Float?,
              metadata: top,
              model: String?,
              model_id: String?,
              model_parameters: ::Hash[Symbol, Langfuse::Models::API::Public::ObservationsView::model_parameter?]?,
              name: String?,
              output: top,
              output_price: Float?,
              parent_observation_id: String?,
              prompt_id: String?,
              prompt_name: String?,
              prompt_version: Integer?,
              status_message: String?,
              time_to_first_token: Float?,
              total_price: Float?,
              trace_id: String?,
              usage: Langfuse::Models::API::Public::Usage?,
              usage_details: ::Hash[Symbol, Integer]?,
              version: String?
            ) -> void
            | (
              ?Langfuse::Models::API::Public::observations_view
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::observations_view

          type model_parameter = (String | Integer | bool | ::Array[String])?

          class ModelParameter < Langfuse::Union
            type string_array = ::Array[String]?

            StringArray: string_array

            private def self.variants: -> [[nil, String], [nil, Integer], [nil, bool], [nil, ::Array[String]]]
          end
        end
      end
    end
  end
end
