module Langfuse
  module Models
    module API
      module Public
        type observation_level = :DEBUG | :DEFAULT | :WARNING | :ERROR

        class ObservationLevel < Langfuse::Enum
          DEBUG: :DEBUG
          DEFAULT: :DEFAULT
          WARNING: :WARNING
          ERROR: :ERROR

          def self.values: -> ::Array[Langfuse::Models::API::Public::observation_level]
        end
      end
    end
  end
end
