module Langfuse
  module Models
    module API
      module Public
        type score_source = :ANNOTATION | :API | :EVAL

        class ScoreSource < Langfuse::Enum
          ANNOTATION: :ANNOTATION
          API: :API
          EVAL: :EVAL

          def self.values: -> ::Array[Langfuse::Models::API::Public::score_source]
        end
      end
    end
  end
end
