module Langfuse
  module Models
    module API
      module Public
        type score_config_create_params =
          {
            data_type: Langfuse::Models::API::Public::score_data_type,
            name: String,
            categories: ::Array[Langfuse::Models::API::Public::ConfigCategory]?,
            description: String?,
            max_value: Float?,
            min_value: Float?
          }
          & Langfuse::request_parameters

        class ScoreConfigCreateParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor data_type: Langfuse::Models::API::Public::score_data_type

          attr_accessor name: String

          attr_accessor categories: ::Array[Langfuse::Models::API::Public::ConfigCategory]?

          attr_accessor description: String?

          attr_accessor max_value: Float?

          attr_accessor min_value: Float?

          def initialize:
            (
              data_type: Langfuse::Models::API::Public::score_data_type,
              name: String,
              categories: ::Array[Langfuse::Models::API::Public::ConfigCategory]?,
              description: String?,
              max_value: Float?,
              min_value: Float?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::score_config_create_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::score_config_create_params
        end
      end
    end
  end
end
