module Langfuse
  module Models
    module API
      module Public
        type score_list_response =
          {
            data: ::Array[Langfuse::Models::API::Public::ScoreListResponse::data],
            meta: Langfuse::Models::API::Public::UtilsMetaResponse
          }

        class ScoreListResponse < Langfuse::BaseModel
          attr_accessor data: ::Array[Langfuse::Models::API::Public::ScoreListResponse::data]

          attr_accessor meta: Langfuse::Models::API::Public::UtilsMetaResponse

          def initialize:
            (
              data: ::Array[Langfuse::Models::API::Public::ScoreListResponse::data],
              meta: Langfuse::Models::API::Public::UtilsMetaResponse
            ) -> void
            | (
              ?Langfuse::Models::API::Public::score_list_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::score_list_response

          type data =
            Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0
            | Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1
            | Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2

          class Data < Langfuse::Union
            type union_member0 =
              {
                data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0::data_type
              }

            class UnionMember0 < Langfuse::Models::API::Public::NumericScore
              attr_reader data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0::data_type?

              def data_type=: (
                Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0::data_type
              ) -> Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0::data_type

              def initialize:
                (
                  data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0::data_type
                ) -> void
                | (
                  ?Langfuse::Models::API::Public::ScoreListResponse::Data::union_member0
                  | Langfuse::BaseModel data
                ) -> void

              def to_hash: -> Langfuse::Models::API::Public::ScoreListResponse::Data::union_member0

              type data_type = :NUMERIC

              class DataType < Langfuse::Enum
                NUMERIC: :NUMERIC

                def self.values: -> ::Array[Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0::data_type]
              end
            end

            type union_member1 =
              {
                data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1::data_type
              }

            class UnionMember1 < Langfuse::Models::API::Public::CategoricalScore
              attr_reader data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1::data_type?

              def data_type=: (
                Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1::data_type
              ) -> Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1::data_type

              def initialize:
                (
                  data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1::data_type
                ) -> void
                | (
                  ?Langfuse::Models::API::Public::ScoreListResponse::Data::union_member1
                  | Langfuse::BaseModel data
                ) -> void

              def to_hash: -> Langfuse::Models::API::Public::ScoreListResponse::Data::union_member1

              type data_type = :CATEGORICAL

              class DataType < Langfuse::Enum
                CATEGORICAL: :CATEGORICAL

                def self.values: -> ::Array[Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1::data_type]
              end
            end

            type union_member2 =
              {
                data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2::data_type
              }

            class UnionMember2 < Langfuse::Models::API::Public::BooleanScore
              attr_reader data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2::data_type?

              def data_type=: (
                Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2::data_type
              ) -> Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2::data_type

              def initialize:
                (
                  data_type: Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2::data_type
                ) -> void
                | (
                  ?Langfuse::Models::API::Public::ScoreListResponse::Data::union_member2
                  | Langfuse::BaseModel data
                ) -> void

              def to_hash: -> Langfuse::Models::API::Public::ScoreListResponse::Data::union_member2

              type data_type = :BOOLEAN

              class DataType < Langfuse::Enum
                BOOLEAN: :BOOLEAN

                def self.values: -> ::Array[Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2::data_type]
              end
            end

            private def self.variants: -> [[nil, Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember0], [nil, Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember1], [nil, Langfuse::Models::API::Public::ScoreListResponse::Data::UnionMember2]]
          end
        end
      end
    end
  end
end
