module Langfuse
  module Models
    module API
      module Public
        type score_create_params =
          {
            name: String,
            trace_id: String,
            value: Langfuse::Models::API::Public::create_score_value,
            id: String?,
            comment: String?,
            config_id: String?,
            data_type: Langfuse::Models::API::Public::score_data_type?,
            environment: String?,
            observation_id: String?
          }
          & Langfuse::request_parameters

        class ScoreCreateParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor name: String

          attr_accessor trace_id: String

          attr_accessor value: Langfuse::Models::API::Public::create_score_value

          attr_accessor id: String?

          attr_accessor comment: String?

          attr_accessor config_id: String?

          attr_accessor data_type: Langfuse::Models::API::Public::score_data_type?

          attr_accessor environment: String?

          attr_accessor observation_id: String?

          def initialize:
            (
              name: String,
              trace_id: String,
              value: Langfuse::Models::API::Public::create_score_value,
              id: String?,
              comment: String?,
              config_id: String?,
              data_type: Langfuse::Models::API::Public::score_data_type?,
              environment: String?,
              observation_id: String?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::score_create_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::score_create_params
        end
      end
    end
  end
end
