module Langfuse
  module Models
    module API
      module Public
        type score_config_list_response =
          {
            data: ::Array[Langfuse::Models::API::Public::ScoreConfig],
            meta: Langfuse::Models::API::Public::UtilsMetaResponse
          }

        class ScoreConfigListResponse < Langfuse::BaseModel
          attr_accessor data: ::Array[Langfuse::Models::API::Public::ScoreConfig]

          attr_accessor meta: Langfuse::Models::API::Public::UtilsMetaResponse

          def initialize:
            (
              data: ::Array[Langfuse::Models::API::Public::ScoreConfig],
              meta: Langfuse::Models::API::Public::UtilsMetaResponse
            ) -> void
            | (
              ?Langfuse::Models::API::Public::score_config_list_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::score_config_list_response
        end
      end
    end
  end
end
