module Langfuse
  module Models
    module API
      module Public
        type score_config =
          {
            id: String,
            created_at: Time,
            data_type: Langfuse::Models::API::Public::score_data_type,
            is_archived: bool,
            name: String,
            project_id: String,
            updated_at: Time,
            categories: ::Array[Langfuse::Models::API::Public::ConfigCategory]?,
            description: String?,
            max_value: Float?,
            min_value: Float?
          }

        class ScoreConfig < Langfuse::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor data_type: Langfuse::Models::API::Public::score_data_type

          attr_accessor is_archived: bool

          attr_accessor name: String

          attr_accessor project_id: String

          attr_accessor updated_at: Time

          attr_accessor categories: ::Array[Langfuse::Models::API::Public::ConfigCategory]?

          attr_accessor description: String?

          attr_accessor max_value: Float?

          attr_accessor min_value: Float?

          def initialize:
            (
              id: String,
              created_at: Time,
              data_type: Langfuse::Models::API::Public::score_data_type,
              is_archived: bool,
              name: String,
              project_id: String,
              updated_at: Time,
              categories: ::Array[Langfuse::Models::API::Public::ConfigCategory]?,
              description: String?,
              max_value: Float?,
              min_value: Float?
            ) -> void
            | (
              ?Langfuse::Models::API::Public::score_config
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::score_config
        end
      end
    end
  end
end
