module Langfuse
  module Models
    module API
      module Public
        type score_data_type = :NUMERIC | :BOOLEAN | :CATEGORICAL

        class ScoreDataType < Langfuse::Enum
          NUMERIC: :NUMERIC
          BOOLEAN: :BOOLEAN
          CATEGORICAL: :CATEGORICAL

          def self.values: -> ::Array[Langfuse::Models::API::Public::score_data_type]
        end
      end
    end
  end
end
