module Langfuse
  module Models
    module API
      module Public
        type session =
          {
            id: String,
            created_at: Time,
            project_id: String,
            environment: String?
          }

        class Session < Langfuse::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Time

          attr_accessor project_id: String

          attr_accessor environment: String?

          def initialize:
            (
              id: String,
              created_at: Time,
              project_id: String,
              environment: String?
            ) -> void
            | (
              ?Langfuse::Models::API::Public::session | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::session
        end
      end
    end
  end
end
