module Langfuse
  module Models
    module API
      module Public
        type session_retrieve_response =
          { traces: ::Array[Langfuse::Models::API::Public::Trace] }

        class SessionRetrieveResponse < Langfuse::Models::API::Public::Session
          attr_accessor traces: ::Array[Langfuse::Models::API::Public::Trace]

          def initialize:
            (traces: ::Array[Langfuse::Models::API::Public::Trace]) -> void
            | (
              ?Langfuse::Models::API::Public::session_retrieve_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::session_retrieve_response
        end
      end
    end
  end
end
