module Langfuse
  module Models
    module API
      module Public
        type trace_delete_multiple_params =
          { trace_ids: ::Array[String] } & Langfuse::request_parameters

        class TraceDeleteMultipleParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_accessor trace_ids: ::Array[String]

          def initialize:
            (
              trace_ids: ::Array[String],
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::trace_delete_multiple_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::trace_delete_multiple_params
        end
      end
    end
  end
end
