module Langfuse
  module Models
    module API
      module Public
        type trace_delete_params = {  } & Langfuse::request_parameters

        class TraceDeleteParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          def initialize:
            (request_options: Langfuse::request_opts) -> void
            | (
              ?Langfuse::Models::API::Public::trace_delete_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::trace_delete_params
        end
      end
    end
  end
end
