module Langfuse
  module Models
    module API
      module Public
        type trace_retrieve_response =
          {
            html_path: String,
            latency: Float,
            observations: ::Array[Langfuse::Models::API::Public::ObservationsView],
            scores: ::Array[Langfuse::Models::API::Public::score],
            total_cost: Float
          }

        class TraceRetrieveResponse < Langfuse::Models::API::Public::Trace
          attr_accessor html_path: String

          attr_accessor latency: Float

          attr_accessor observations: ::Array[Langfuse::Models::API::Public::ObservationsView]

          attr_accessor scores: ::Array[Langfuse::Models::API::Public::score]

          attr_accessor total_cost: Float

          def initialize:
            (
              html_path: String,
              latency: Float,
              observations: ::Array[Langfuse::Models::API::Public::ObservationsView],
              scores: ::Array[Langfuse::Models::API::Public::score],
              total_cost: Float
            ) -> void
            | (
              ?Langfuse::Models::API::Public::trace_retrieve_response
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::trace_retrieve_response
        end
      end
    end
  end
end
