module Langfuse
  module Models
    module API
      module Public
        type trace_list_params =
          {
            environment: ::Array[String?],
            from_timestamp: Time?,
            limit: Integer?,
            name: String?,
            order_by: String?,
            page: Integer?,
            release: String?,
            session_id: String?,
            tags: ::Array[String?],
            to_timestamp: Time?,
            user_id: String?,
            version: String?
          }
          & Langfuse::request_parameters

        class TraceListParams < Langfuse::BaseModel
          extend Langfuse::RequestParameters::Converter
          include Langfuse::RequestParameters

          attr_reader environment: ::Array[String?]?

          def environment=: (::Array[String?]) -> ::Array[String?]

          attr_accessor from_timestamp: Time?

          attr_accessor limit: Integer?

          attr_accessor name: String?

          attr_accessor order_by: String?

          attr_accessor page: Integer?

          attr_accessor release: String?

          attr_accessor session_id: String?

          attr_reader tags: ::Array[String?]?

          def tags=: (::Array[String?]) -> ::Array[String?]

          attr_accessor to_timestamp: Time?

          attr_accessor user_id: String?

          attr_accessor version: String?

          def initialize:
            (
              environment: ::Array[String?],
              from_timestamp: Time?,
              limit: Integer?,
              name: String?,
              order_by: String?,
              page: Integer?,
              release: String?,
              session_id: String?,
              tags: ::Array[String?],
              to_timestamp: Time?,
              user_id: String?,
              version: String?,
              request_options: Langfuse::request_opts
            ) -> void
            | (
              ?Langfuse::Models::API::Public::trace_list_params
              | Langfuse::BaseModel data
            ) -> void

          def to_hash: -> Langfuse::Models::API::Public::trace_list_params
        end
      end
    end
  end
end
