# frozen_string_literal: true

module Langfuse
  module Resources
    class API
      class Public
        class ScoreConfigs
          # Create a score configuration (config). Score configs are used to define the
          #   structure of scores
          #
          # @param params [Langfuse::Models::API::Public::ScoreConfigCreateParams, Hash{Symbol=>Object}] .
          #
          #   @option params [Symbol, Langfuse::Models::API::Public::ScoreDataType] :data_type
          #
          #   @option params [String] :name
          #
          #   @option params [Array<Langfuse::Models::API::Public::ConfigCategory>, nil] :categories Configure custom categories for categorical scores. Pass a list of objects with
          #     `label` and `value` properties. Categories are autogenerated for boolean configs
          #     and cannot be passed
          #
          #   @option params [String, nil] :description Description is shown across the Langfuse UI and can be used to e.g. explain the
          #     config categories in detail, why a numeric range was set, or provide additional
          #     context on config name or usage
          #
          #   @option params [Float, nil] :max_value Configure a maximum value for numerical scores. If not set, the maximum value
          #     defaults to +∞
          #
          #   @option params [Float, nil] :min_value Configure a minimum value for numerical scores. If not set, the minimum value
          #     defaults to -∞
          #
          #   @option params [Langfuse::RequestOptions, Hash{Symbol=>Object}, nil] :request_options
          #
          # @return [Langfuse::Models::API::Public::ScoreConfig]
          #
          def create(params)
            parsed, options = Langfuse::Models::API::Public::ScoreConfigCreateParams.dump_request(params)
            @client.request(
              method: :post,
              path: "api/public/score-configs",
              body: parsed,
              model: Langfuse::Models::API::Public::ScoreConfig,
              options: options
            )
          end

          # Get a score config
          #
          # @param config_id [String] The unique langfuse identifier of a score config
          #
          # @param params [Langfuse::Models::API::Public::ScoreConfigRetrieveParams, Hash{Symbol=>Object}] .
          #
          #   @option params [Langfuse::RequestOptions, Hash{Symbol=>Object}, nil] :request_options
          #
          # @return [Langfuse::Models::API::Public::ScoreConfig]
          #
          def retrieve(config_id, params = {})
            @client.request(
              method: :get,
              path: ["api/public/score-configs/%0s", config_id],
              model: Langfuse::Models::API::Public::ScoreConfig,
              options: params[:request_options]
            )
          end

          # Get all score configs
          #
          # @param params [Langfuse::Models::API::Public::ScoreConfigListParams, Hash{Symbol=>Object}] .
          #
          #   @option params [Integer, nil] :limit Limit of items per page. If you encounter api issues due to too large page
          #     sizes, try to reduce the limit
          #
          #   @option params [Integer, nil] :page Page number, starts at 1.
          #
          #   @option params [Langfuse::RequestOptions, Hash{Symbol=>Object}, nil] :request_options
          #
          # @return [Langfuse::Models::API::Public::ScoreConfigListResponse]
          #
          def list(params = {})
            parsed, options = Langfuse::Models::API::Public::ScoreConfigListParams.dump_request(params)
            @client.request(
              method: :get,
              path: "api/public/score-configs",
              query: parsed,
              model: Langfuse::Models::API::Public::ScoreConfigListResponse,
              options: options
            )
          end

          # @param client [Langfuse::Client]
          #
          def initialize(client:)
            @client = client
          end
        end
      end
    end
  end
end
